# Generated by Django 4.2 on 2023-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
