# Generated by Django 4.2 on 2023-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_customuser_image_alter_customuser_indexno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
