# Generated by Django 4.2 on 2023-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_program_programname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='programName',
            field=models.CharField(max_length=255),
        ),
    ]
